# Group By Operation on Fortune 500 Companies

In [33]:
import pandas as pd

In [44]:
companies = pd.read_excel('companies.xlsx')
print(f"The total number of rows in the DataFrame is: {companies.shape[0]}")
print(f"The total number of cols in the DataFrame is: {companies.shape[1]}")

The total number of rows in the DataFrame is: 500
The total number of cols in the DataFrame is: 12

In [45]:
companies

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value,Sector,Industry
0,1,Walmart,"23,00,000",1.0,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619",Consumer Staples,Food & Staples Retailing
1,2,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035",Financials,Multi-Sector Holdings
2,3,Apple,"1,16,000",3.0,"$2,15,639",-7.7%,"$45,687.0",-14.4%,"$3,21,686","$7,53,718",Information Technology,"Technology Hardware, Storage & Peripherals"
3,4,Exxon Mobil,"72,700",2.0,"$2,05,004",-16.7%,"$7,840.0",-51.5%,"$3,30,314","$3,40,056",Energy,Oil & Gas
4,5,McKesson,"68,000",5.0,"$1,92,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439",Health Care,Health Care Distributors
...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Michaels Cos.,"31,000",517.0,"$5,197",5.8%,$378.2,4.2%,"$2,148","$4,229",Consumer Discretionary,Specialty Retail
496,497,Toll Brothers,"4,200",576.0,"$5,170",23.9%,$382.1,5.2%,"$9,737","$5,872",Consumer Discretionary,Homebuilding
497,498,Yahoo,"8,500",513.0,"$5,169",4.0%,-$214.3,-,"$48,083","$44,391",Communication Services,Interactive Media & Services
498,499,Vistra Energy,"4,431",NaN,"$5,164",-,-,-,"$15,167","$6,968",Utilities,Independent Power Producers
499,500,ABM Industries,"1,10,000",485.0,"$5,145",-2.8%,$57.2,-25.0%,"$2,281","$2,428",Industrials,Diversified Support Services

### Getting the information about the companies data

In [46]:
companies.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Rank                 500 non-null    int64
 1   Company Name         500 non-null    str
 2   Number of Employees  500 non-null    str
 3   Previous Rank        492 non-null    float64
 4   Revenues             500 non-null    str
 5   Revenue Change       500 non-null    str
 6   Profits              500 non-null    str
 7   Profit Change        500 non-null    str
 8   Assets               500 non-null    str
 9   Market Value         500 non-null    str
 10  Sector               500 non-null    str
 11  Industry             500 non-null    str
dtypes: float64(1), int64(1), str(10)
memory usage: 47.0 KB

### Group by operation

In [47]:
sectors = companies.groupby('Sector')

In [50]:
print(f"The number of companies in the DataFrame is: {len(companies)}")
print(f"After dividing companies in the sectors is: {len(sectors)}")

The number of companies in the DataFrame is: 500
After dividing companies in the sectors is: 11

                        Rank                                                \
                       count        mean         std    min     25%    50%
Sector
Communication Services  26.0  236.653846  161.768215    9.0   96.50  208.5
Consumer Discretionary  84.0  265.642857  131.033578    8.0  160.00  269.5
Consumer Staples        45.0  209.333333  148.018426    1.0   85.00  176.0
Energy                  30.0  227.900000  140.640983    4.0  115.50  234.0
Financials              83.0  248.831325  155.108917    2.0   98.00  246.0
Health Care             46.0  179.956522  136.433615    5.0   63.75  145.5
Industrials             74.0  271.513514  145.223328   13.0  143.75  283.0
Information Technology  45.0  247.422222  152.403395    3.0  109.00  226.0
Materials               34.0  304.823529  112.049359   62.0  215.25  307.5
Real Estate              7.0  398.857143   94.839212  214.0  366.00  448.0
Utilities               26.0  277.423077  111.008531   89.0  194.50  259.5

                                      Previous Rank                          \
                           75%    max         count        mean         std
Sector
Communication Services  342.75  498.0          26.0  261.346154  170.705581
Consumer Discretionary  374.00  497.0          83.0  280.072289  146.282869
Consumer Staples        346.00  486.0          44.0  221.318182  160.587841
Energy                  343.75  488.0          30.0  192.666667  125.347058
Financials              401.00  484.0          82.0  256.000000  164.940917
Health Care             279.75  466.0          46.0  196.913043  150.531034
Industrials             392.75  500.0          74.0  271.337838  150.215487
Information Technology  387.00  481.0          43.0  266.674419  164.261221
Materials               396.50  489.0          32.0  304.687500  141.424649
Real Estate             460.50  477.0           7.0  429.000000   88.716778
Utilities               364.25  499.0          25.0  263.640000  100.380891


                          min     25%    50%     75%    max
Sector
Communication Services   10.0  113.50  252.5  399.25  532.0
Consumer Discretionary    8.0  173.00  284.0  375.50  640.0
Consumer Staples          1.0   86.25  178.5  340.50  686.0
Energy                    2.0   93.50  195.0  285.75  445.0
Financials                4.0   88.75  251.0  400.25  540.0
Health Care               5.0   65.25  152.5  290.75  559.0
Industrials              11.0  142.50  269.5  390.75  637.0
Information Technology    3.0  114.50  233.0  408.50  524.0
Materials                56.0  201.75  299.5  377.00  761.0
Real Estate             259.0  404.50  449.0  480.00  526.0
Utilities                95.0  188.00  247.0  350.00  437.0