# Group By Operation on Fortune 500 Companies

In [2]:
import pandas as pd

In [35]:
companies = pd.read_excel('companies.xlsx')
print(f"The total number of rows in the DataFrame is: {companies.shape[0]}")
print(f"The total number of cols in the DataFrame is: {companies.shape[1]}")

The total number of rows in the DataFrame is: 500
The total number of cols in the DataFrame is: 12

In [36]:
companies

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value,Sector,Industry
0,1,Walmart,"23,00,000",1.0,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619",Consumer Staples,Food & Staples Retailing
1,2,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035",Financials,Multi-Sector Holdings
2,3,Apple,"1,16,000",3.0,"$2,15,639",-7.7%,"$45,687.0",-14.4%,"$3,21,686","$7,53,718",Information Technology,"Technology Hardware, Storage & Peripherals"
3,4,Exxon Mobil,"72,700",2.0,"$2,05,004",-16.7%,"$7,840.0",-51.5%,"$3,30,314","$3,40,056",Energy,Oil & Gas
4,5,McKesson,"68,000",5.0,"$1,92,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439",Health Care,Health Care Distributors
...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Michaels Cos.,"31,000",517.0,"$5,197",5.8%,$378.2,4.2%,"$2,148","$4,229",Consumer Discretionary,Specialty Retail
496,497,Toll Brothers,"4,200",576.0,"$5,170",23.9%,$382.1,5.2%,"$9,737","$5,872",Consumer Discretionary,Homebuilding
497,498,Yahoo,"8,500",513.0,"$5,169",4.0%,-$214.3,-,"$48,083","$44,391",Communication Services,Interactive Media & Services
498,499,Vistra Energy,"4,431",NaN,"$5,164",-,-,-,"$15,167","$6,968",Utilities,Independent Power Producers
499,500,ABM Industries,"1,10,000",485.0,"$5,145",-2.8%,$57.2,-25.0%,"$2,281","$2,428",Industrials,Diversified Support Services

### Getting the information about the companies data

In [37]:
companies.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Rank                 500 non-null    int64
 1   Company Name         500 non-null    str
 2   Number of Employees  500 non-null    str
 3   Previous Rank        492 non-null    float64
 4   Revenues             500 non-null    str
 5   Revenue Change       500 non-null    str
 6   Profits              500 non-null    str
 7   Profit Change        500 non-null    str
 8   Assets               500 non-null    str
 9   Market Value         500 non-null    str
 10  Sector               500 non-null    str
 11  Industry             500 non-null    str
dtypes: float64(1), int64(1), str(10)
memory usage: 47.0 KB

### Group by operation

In [38]:
sectors = companies.groupby('Sector')

In [39]:
print(f"The number of companies in the DataFrame is: {len(companies)}")
print(f"After dividing companies in the sectors is: {len(sectors)}")

The number of companies in the DataFrame is: 500
After dividing companies in the sectors is: 11

In [40]:
sectors

### Find the size of the sectors from companies DataFrame

In [41]:
sectors.size()

Sector
Communication Services    26
Consumer Discretionary    84
Consumer Staples          45
Energy                    30
Financials                83
Health Care               46
Industrials               74
Information Technology    45
Materials                 34
Real Estate                7
Utilities                 26
dtype: int64

In [42]:
sectors.size().sort_values(ascending=False)

Sector
Consumer Discretionary    84
Financials                83
Industrials               74
Health Care               46
Consumer Staples          45
Information Technology    45
Materials                 34
Energy                    30
Communication Services    26
Utilities                 26
Real Estate                7
dtype: int64

### first()
This method will return the first occurrence of the matching sector

In [43]:
sectors.first()

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value,Industry
Sector,,,,,,,,,,,
Communication Services,9,AT&T,"2,68,540",10.0,"$1,63,786",11.6%,"$12,976.0",-2.8%,"$4,03,821","$2,55,679",Integrated Telecommunication Services
Consumer Discretionary,8,General Motors,"2,25,000",8.0,"$1,66,380",9.2%,"$9,427.0",-2.7%,"$2,21,690","$52,968",Automobile Manufacturers
Consumer Staples,1,Walmart,"23,00,000",1.0,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619",Food & Staples Retailing
Energy,4,Exxon Mobil,"72,700",2.0,"$2,05,004",-16.7%,"$7,840.0",-51.5%,"$3,30,314","$3,40,056",Oil & Gas
Financials,2,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035",Multi-Sector Holdings
Health Care,5,McKesson,"68,000",5.0,"$1,92,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439",Health Care Distributors
Industrials,13,General Electric,"2,95,000",11.0,"$1,26,661",-9.8%,"$8,831.0",-,"$3,65,183","$2,59,520",Industrial Conglomerates
Information Technology,3,Apple,"1,16,000",3.0,"$2,15,639",-7.7%,"$45,687.0",-14.4%,"$3,21,686","$7,53,718","Technology Hardware, Storage & Peripherals"
Materials,62,Dow Chemical,"56,000",56.0,"$48,158",-1.3%,"$4,318.0",-43.8%,"$79,511","$77,460",Commodity Chemicals
Real Estate,214,CBRE Group,"75,000",259.0,"$13,072",20.4%,$572.0,4.5%,"$10,780","$11,753",Real Estate Services
Utilities,89,Exelon,"34,396",95.0,"$31,360",6.5%,"$1,134.0",-50.0%,"$1,14,904","$33,309",Multi-Utilities

### last()
This method will return the last occurrence of the matching sector

In [44]:
sectors.last()

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value,Industry
Sector,,,,,,,,,,,
Communication Services,498,Yahoo,"8,500",513.0,"$5,169",4.0%,-$214.3,-,"$48,083","$44,391",Interactive Media & Services
Consumer Discretionary,497,Toll Brothers,"4,200",576.0,"$5,170",23.9%,$382.1,5.2%,"$9,737","$5,872",Homebuilding
Consumer Staples,486,Seaboard,"11,781",460.0,"$5,379",-3.8%,$312.0,82.5%,"$4,755","$4,881",Agricultural Products
Energy,488,Apache,"3,727",388.0,"$5,354",-19.5%,"-$1,405.0",-,"$22,519","$19,547",Oil & Gas
Financials,484,Regions Financial,"7,293",453.0,"$5,389",-5.0%,$900.0,196.1%,"$8,357","$12,643",Diversified Banks
Health Care,466,Patterson,"7,000",559.0,"$5,555",27.0%,$187.2,-16.2%,"$3,521","$4,393",Health Care Distributors
Industrials,500,ABM Industries,"1,10,000",485.0,"$5,145",-2.8%,$57.2,-25.0%,"$2,281","$2,428",Diversified Support Services
Information Technology,481,Booz Allen Hamilton Holding,"22,600",487.0,"$5,406",2.5%,$294.1,26.5%,"$3,010","$5,307",IT Consulting & Other Services
Materials,489,Airgas,"17,000",484.0,"$5,314",0.2%,$337.5,-8.3%,"$6,135",-,Industrial Gases
Real Estate,477,Simon Property Group,"4,050",488.0,"$5,435",3.2%,"$1,838.9",0.6%,"$31,104","$53,732",Retail REITs
Utilities,499,Vistra Energy,"4,431",384.0,"$5,164",-,-,-,"$15,167","$6,968",Independent Power Producers

### groups
This attribute returns the list of index of the groupby sectors

In [45]:
sectors.groups

{'Communication Services': [8, 13, 26, 30, 51, 94, 95, 97, 100, 159, 178, 185, 192, 223, 312, 313, 329, 331, 335, 344, 405, 411, 425, 484, 490, 497], 'Consumer Discretionary': [7, 9, 11, 22, 37, 39, 71, 86, 87, 109, 111, 126, 127, 128, 130, 135, 136, 139, 141, 149, 150, 162, 173, 177, 179, 183, 187, 202, 207, 218, 219, 220, 229, 231, 232, 240, 243, 248, 259, 260, 267, 268, 269, 282, 286, 290, 291, 296, 303, 304, 306, 309, 310, 316, 317, 320, 321, 322, 334, 339, 347, 352, 370, 382, 383, 384, 385, 395, 398, 409, 414, 416, 421, 431, 434, 445, 446, 460, 462, 469, 473, 494, 495, 496], 'Consumer Staples': [0, 15, 16, 17, 35, 43, 44, 48, 56, 63, 81, 84, 90, 92, 103, 105, 123, 147, 154, 157, 164, 170, 175, 181, 196, 208, 215, 222, 246, 252, 294, 324, 338, 345, 349, 350, 368, 407, 415, 422, 426, 443, 452, 455, 485], 'Energy': [3, 18, 33, 36, 50, 78, 102, 114, 116, 121, 140, 171, 172, 214, 230, 236, 273, 277, 284, 311, 333, 342, 343, 348, 355, 366, 374, 401, 479, 487], 'Financials': [1, 19, 20, 24, 25, 29, 32, 38, 41, 47, 54, 64, 67, 74, 75, 76, 77, 79, 83, 85, 96, 98, 99, 101, 119, 124, 125, 152, 165, 167, 176, 184, 188, 206, 209, 212, 217, 221, 226, 238, 244, 245, 254, 257, 261, 265, 270, 276, 285, 292, 301, 302, 314, 315, 328, 341, 353, 356, 360, 381, 388, 397, 403, 404, 410, 417, 427, 435, 436, 438, 450, 454, 458, 459, 461, 463, 468, 474, 475, 477, 478, 482, 483], 'Health Care': [4, 5, 6, 10, 14, 21, 28, 34, 42, 52, 53, 62, 65, 68, 69, 91, 110, 122, 129, 131, 133, 134, 143, 146, 153, 155, 180, 194, 224, 242, 247, 251, 253, 275, 280, 287, 289, 326, 351, 365, 373, 375, 389, 433, 453, 465], 'Industrials': [12, 23, 45, 49, 55, 57, 66, 70, 72, 73, 82, 89, 93, 104, 113, 115, 137, 138, 142, 145, 148, 158, 160, 163, 190, 191, 199, 200, 201, 211, 239, 249, 250, 256, 258, 272, 281, 283, 295, 298, 318, 323, 330, 336, 354, 358, 359, 362, 363, 369, 371, 372, 379, 387, 391, 392, 393, 402, 406, 419, 420, 424, 428, 437, 441, 444, 451, 457, 486, 489, 491, 492, 493, 499], 'Information Technology': [2, 27, 31, 40, 46, 58, 59, 60, 80, 106, 107, 108, 117, 118, 151, 161, 186, 197, 198, 204, 205, 216, 225, 241, 263, 264, 266, 297, 300, 325, 377, 378, 380, 386, 408, 413, 423, 432, 439, 442, 464, 467, 470, 472, 480], 'Materials': [61, 112, 132, 168, 174, 182, 189, 203, 210, 227, 235, 274, 278, 288, 293, 299, 305, 308, 319, 327, 332, 337, 346, 376, 394, 396, 400, 412, 429, 440, 449, 466, 481, 488], 'Real Estate': [213, 340, 390, 447, 448, 471, 476], 'Utilities': [88, 120, 144, 156, 166, 169, 193, 195, 228, 233, 234, 237, 255, 262, 271, 279, 307, 357, 361, 364, 367, 399, 418, 430, 456, 498]}

### To verify if the groups attribute has returned the right indices

In [46]:
companies.iloc[[8, 13, 26, 30]]

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value,Sector,Industry
8,9,AT&T,"2,68,540",10.0,"$1,63,786",11.6%,"$12,976.0",-2.8%,"$4,03,821","$2,55,679",Communication Services,Integrated Telecommunication Services
13,14,Verizon,"1,60,900",13.0,"$1,25,980",-4.3%,"$13,127.0",-26.6%,"$2,44,180","$1,98,900",Communication Services,Integrated Telecommunication Services
26,27,Alphabet,"72,053",36.0,"$90,272",20.4%,"$19,478.0",19.1%,"$1,67,497","$5,79,426",Communication Services,Interactive Media & Services
30,31,Comcast,"1,59,000",37.0,"$80,403",7.9%,"$8,695.0",6.5%,"$1,80,500","$1,78,258",Communication Services,Cable & Satellite

### get_group()
This method returns the DataFrame of the particular group

In [47]:
sectors.get_group('Health Care')

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value,Sector,Industry
4,5,McKesson,"68,000",5.0,"$1,92,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439",Health Care,Health Care Distributors
5,6,UnitedHealth Group,"2,30,000",6.0,"$1,84,840",17.7%,"$7,017.0",20.7%,"$1,22,810","$1,57,793",Health Care,Managed Health Care
6,7,CVS Health,"2,04,000",7.0,"$1,77,526",15.8%,"$5,317.0",1.5%,"$94,462","$81,310",Health Care,Health Care Services
10,11,AmerisourceBergen,"18,500",12.0,"$1,46,850",8.0%,"$1,427.9",-,"$33,656","$19,229",Health Care,Health Care Distributors
14,15,Cardinal Health,"37,300",21.0,"$1,21,546",18.5%,"$1,427.0",17.4%,"$34,122","$25,725",Health Care,Health Care Distributors
21,22,Express Scripts Holding,"25,600",22.0,"$1,00,288",-1.4%,"$3,404.4",37.5%,"$51,745","$39,567",Health Care,Health Care Services
28,29,Anthem,"53,000",33.0,"$84,863",7.2%,"$2,469.8",-3.5%,"$65,083","$43,813",Health Care,Managed Health Care
34,35,Johnson & Johnson,"1,26,400",39.0,"$71,890",2.6%,"$16,540.0",7.3%,"$1,41,208","$3,37,642",Health Care,Pharmaceuticals
42,43,Aetna,"49,500",46.0,"$63,155",4.7%,"$2,271.0",-5.0%,"$69,146","$44,859",Health Care,Managed Health Care
52,53,Humana,"51,600",52.0,"$54,379",0.2%,$614.0,-51.9%,"$25,396","$29,743",Health Care,Managed Health Care
53,54,Pfizer,"96,500",55.0,"$52,824",8.1%,"$7,215.0",3.7%,"$1,71,615","$2,03,725",Health Care,Pharmaceuticals
62,63,HCA Holdings,"2,10,500",63.0,"$44,747",2.7%,"$2,890.0",35.7%,"$33,758","$32,966",Health Care,Health Care Facilities
65,66,Centene,"30,500",124.0,"$40,721",78.6%,$562.0,58.3%,"$20,197","$12,271",Health Care,Managed Health Care
68,69,Merck,"68,000",72.0,"$39,807",0.8%,"$3,920.0",-11.8%,"$95,377","$1,74,454",Health Care,Pharmaceuticals
69,70,Cigna,"41,000",79.0,"$39,668",4.7%,"$1,867.0",-10.8%,"$59,360","$37,604",Health Care,Managed Health Care
91,92,Gilead Sciences,"9,000",86.0,"$30,390",-6.9%,"$13,501.0",-25.4%,"$56,977","$88,788",Health Care,Biotechnology
110,111,AbbVie,"30,000",123.0,"$25,638",12.2%,"$5,953.0",15.7%,"$66,099","$1,03,838",Health Care,Biotechnology
122,123,Amgen,"19,200",130.0,"$22,991",6.1%,"$7,722.0",11.3%,"$77,626","$1,20,830",Health Care,Biotechnology
129,130,Community Health Systems,"1,08,000",125.0,"$21,374",-5.8%,"-$1,721.0",-,"$21,944","$1,010",Health Care,Health Care Facilities
131,132,Eli Lilly,"41,975",141.0,"$21,222",6.3%,"$2,737.6",13.7%,"$38,806","$92,803",Health Care,Pharmaceuticals
133,134,Tenet Healthcare,"1,16,475",140.0,"$21,070",4.8%,-$192.0,-,"$24,701","$1,777",Health Care,Health Care Facilities
134,135,Abbott Laboratories,"75,000",138.0,"$20,853",0.9%,"$1,400.0",-68.3%,"$52,666","$76,740",Health Care,Health Care Equipment
143,144,Danaher,"62,000",133.0,"$19,912",-4.8%,"$2,553.7",-23.9%,"$45,295","$59,359",Health Care,Health Care Equipment
146,147,Bristol-Myers Squibb,"25,000",168.0,"$19,427",17.3%,"$4,457.0",184.8%,"$33,707","$89,591",Health Care,Pharmaceuticals
153,154,Thermo Fisher Scientific,"54,800",164.0,"$18,274",7.7%,"$2,021.8",2.3%,"$45,908","$59,964",Health Care,Life Sciences Tools & Services
155,156,Molina Healthcare,"21,000",201.0,"$17,782",25.4%,$52.0,-63.6%,"$7,449","$2,601",Health Care,Managed Health Care
180,181,DaVita HealthCare Partners,"70,300",200.0,"$15,197",6.9%,$879.9,226.2%,"$18,741","$13,227",Health Care,Health Care Facilities
194,195,WellCare Health Plans,"7,400",202.0,"$14,237",2.5%,$242.1,104.1%,"$6,153","$6,212",Health Care,Managed Health Care
224,225,Becton Dickinson,"50,928",278.0,"$12,483",21.4%,$976.0,40.4%,"$25,586","$39,041",Health Care,Health Care Equipment
242,243,Henry Schein,"21,000",268.0,"$11,572",8.9%,$506.8,5.8%,"$6,730","$13,461",Health Care,Health Care Distributors
247,248,Biogen,"7,400",263.0,"$11,449",6.4%,"$3,702.8",4.4%,"$22,877","$59,046",Health Care,Biotechnology
251,252,Stryker,"33,000",287.0,"$11,325",13.9%,"$1,647.0",14.5%,"$20,435","$49,115",Health Care,Health Care Equipment
253,254,Celgene,"7,132",305.0,"$11,229",21.3%,"$1,999.2",24.8%,"$28,086","$96,802",Health Care,Biotechnology
275,276,Universal Health Services,"70,863",290.0,"$10,508",7.4%,$702.4,3.2%,"$10,318","$12,022",Health Care,Health Care Facilities
280,281,Baxter International,"48,000",286.0,"$10,163",2.0%,"$4,965.0",412.9%,"$15,546","$28,106",Health Care,Health Care Equipment
287,288,Owens & Minor,"7,900",291.0,"$9,723",-0.5%,$108.8,5.2%,"$2,718","$2,114",Health Care,Health Care Distributors
289,290,Laboratory Corp. of America,"52,000",325.0,"$9,642",11.1%,$732.1,67.6%,"$14,247","$14,696",Health Care,Health Care Services
326,327,Boston Scientific,"27,000",359.0,"$8,386",12.2%,$347.0,-,"$18,096","$34,046",Health Care,Health Care Equipment
351,352,Zimmer Biomet Holdings,"18,500",431.0,"$7,684",28.1%,$305.9,108.1%,"$26,684","$24,571",Health Care,Health Care Equipment
365,366,Quest Diagnostics,"43,000",358.0,"$7,515",0.3%,$645.0,-9.0%,"$10,100","$13,501",Health Care,Health Care Services
373,374,LifePoint Health,"47,000",430.0,"$7,274",20.9%,$121.9,-33.0%,"$6,319","$2,616",Health Care,Health Care Facilities
375,376,Kindred Healthcare,"76,650",372.0,"$7,227",1.8%,-$664.2,-,"$6,113",$711,Health Care,Health Care Facilities
389,390,Quintiles Transnational Holdings,"50,000",447.0,"$6,878",19.9%,$115.0,-70.3%,"$21,208","$18,999",Health Care,Life Sciences Tools & Services
433,434,St. Jude Medical,"18,000",465.0,"$6,004",8.4%,$734.0,-16.6%,"$12,578",-,Health Care,Health Care Equipment
453,454,Genesis Healthcare,"82,000",457.0,"$5,733",2.0%,-$64.0,-,"$5,779",$408,Health Care,Health Care Facilities
465,466,Patterson,"7,000",559.0,"$5,555",27.0%,$187.2,-16.2%,"$3,521","$4,393",Health Care,Health Care Distributors

### sum()
This method returns the sum of a DataFrame of all numerical cols

In [48]:
sectors.sum()

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value,Industry
Sector,,,,,,,,,,,
Communication Services,6153,AT&TVerizonAlphabetComcastDisneyTime WarnerCha...,"2,68,5401,60,90072,0531,59,0001,95,00025,00091...",6795.0,"$1,63,786$1,25,980$90,272$80,403$55,632$29,318...",11.6%-4.3%20.4%7.9%6.0%4.3%197.3%54.2%-5.7%-2....,"$12,976.0$13,127.0$19,478.0$8,695.0$9,391.0$3,...",-2.8%-26.6%19.1%6.5%12.0%2.4%-177.0%-66.8%-28....,"$4,03,821$2,44,180$1,67,497$1,80,500$92,033$65...","$2,55,679$1,98,900$5,79,426$1,78,258$1,79,298$...",Integrated Telecommunication ServicesIntegrate...
Consumer Discretionary,22314,General MotorsFord MotorAmazon.comHome DepotTa...,"2,25,0002,01,0003,41,4004,06,0003,23,0002,40,0...",23246.0,"$1,66,380$1,51,800$1,35,987$94,595$69,495$65,0...",9.2%1.5%27.1%6.9%-5.8%10.1%-0.9%7.2%5.8%-4.8%-...,"$9,427.0$4,596.0$2,371.0$7,957.0$2,737.0$3,093...",-2.7%-37.7%297.8%13.5%-18.6%21.5%36.9%0.9%14.9...,"$2,21,690$2,37,951$83,402$42,966$37,431$34,408...","$52,968$46,349$4,23,031$1,76,368$30,502$70,481...",Automobile ManufacturersAutomobile Manufacture...
Consumer Staples,9420,WalmartCostcoWalgreens Boots AllianceKrogerPro...,"23,00,0001,72,0003,00,0004,43,0001,05,0002,64,...",9738.0,"$4,85,873$1,18,719$1,17,351$1,15,337$71,726$62...",0.8%2.2%13.4%5.0%-8.9%-0.4%-7.9%115.9%3.5%-5.5...,"$13,643.0$2,350.0$4,173.0$1,975.0$10,508.0$6,3...",-7.2%-1.1%-1.1%-3.1%49.3%16.1%-30.8%-38.3%-11....,"$1,98,825$33,163$72,688$36,505$1,27,136$74,129...","$2,18,619$73,606$89,645$26,961$2,29,700$1,59,7...",Food & Staples RetailingFood & Staples Retaili...
Energy,6837,Exxon MobilChevronPhillips 66Valero EnergyMara...,"72,70055,20014,8009,99644,46030,9925,00013,300...",5780.0,"$2,05,004$1,07,567$72,396$70,166$55,858$37,504...",-16.7%-18.0%-16.9%-14.2%-13.5%-11.0%-11.1%-21....,"$7,840.0-$497.0$1,555.0$2,289.0$1,174.0$995.0$...",-51.5%-110.8%-63.2%-42.6%-58.8%-16.3%-27.5%--5...,"$3,30,314$2,60,078$51,653$46,173$44,413$79,011...","$3,40,056$2,03,263$40,954$29,746$26,679$21,292...",Oil & GasOil & GasOil & Gas Refining & Marketi...
Financials,20653,Berkshire HathawayFannie MaeJ.P. Morgan ChaseW...,"3,67,7007,0002,43,3552,69,1002,08,0242,19,0006...",20992.0,"$2,23,604$1,07,162$1,05,486$94,176$93,662$82,3...",6.1%-2.9%4.4%4.6%0.7%-6.7%0.6%3.4%-9.3%2.9%-10...,"$24,074.0$12,313.0$24,733.0$21,938.0$17,906.0$...",0.0%12.4%1.2%-4.2%12.7%-13.5%-94.4%22.6%-84.9%...,"$6,20,854$32,87,968$24,90,972$19,30,115$21,87,...","$4,11,035$3,011$3,13,761$2,78,516$2,36,182$1,6...",Multi-Sector HoldingsThrifts & Mortgage Financ...
Health Care,8278,McKessonUnitedHealth GroupCVS HealthAmerisourc...,"68,0002,30,0002,04,00018,50037,30025,60053,000...",9058.0,"$1,92,487$1,84,840$1,77,526$1,46,850$1,21,546$...",6.2%17.7%15.8%8.0%18.5%-1.4%7.2%2.6%4.7%0.2%8....,"$2,258.0$7,017.0$5,317.0$1,427.9$1,427.0$3,404...",53.0%20.7%1.5%-17.4%37.5%-3.5%7.3%-5.0%-51.9%3...,"$56,563$1,22,810$94,462$33,656$34,122$51,745$6...","$31,439$1,57,793$81,310$19,229$25,725$39,567$4...",Health Care DistributorsManaged Health CareHea...
Industrials,20092,General ElectricBoeingUPSUnited TechnologiesLo...,"2,95,0001,50,5403,35,5202,01,60097,0003,35,767...",20079.0,"$1,26,661$94,571$60,906$57,244$50,658$50,365$4...",-9.8%-1.6%4.4%-6.2%9.8%6.1%-2.0%-2.6%1.9%-18.0...,"$8,831.0$4,895.0$3,431.0$5,055.0$5,302.0$1,820...",--5.4%-29.2%-33.6%47.1%73.3%-64.8%-3.4%0.9%-10...,"$3,65,183$89,997$40,377$89,706$47,806$46,064$5...","$2,59,520$1,07,546$93,276$89,957$77,557$52,178...",Industrial ConglomeratesAerospace & DefenseAir...
Information Technology,11134,AppleMicrosoftIBMDell TechnologiesIntelHewlett...,"1,16,0001,14,0004,14,4001,38,0001,06,0001,95,0...",11467.0,"$2,15,639$85,320$79,919$64,806$59,387$50,123$4...",-7.7%-8.8%-3.1%18.1%7.3%-0.2%-53.3%-3.1%-0.5%-...,"$45,687.0$16,798.0$11,872.0-$1,672.0$10,316.0$...",-14.4%37.8%-10.0%--9.7%-19.6%-45.2%-10.4%-26.6...,"$3,21,686$1,93,694$1,17,470$1,18,206$1,13,327$...","$7,53,718$5,08,935$1,64,251-$1,70,539$39,288$1...","Technology Hardware, Storage & PeripheralsSyst..."
Materials,10364,Dow ChemicalDuPontInternational PaperNucorFree...,"56,00046,00055,00023,90030,00047,00039,00022,4...",9750.0,"$48,158$24,594$21,079$16,208$15,789$15,178$14,...",-1.3%-12.0%-5.8%-1.4%-0.6%-1.0%29.2%-10.0%-2.9...,"$4,318.0$2,513.0$904.0$796.3-$4,154.0$877.0-$3...",-43.8%28.7%-3.6%122.6%--37.6%-178.2%-42.3%22.7...,"$79,511$39,964$33,345$15,224$37,317$15,769$23,...","$77,460$69,451$20,884$19,051$19,310$26,970$13,...",Commodity ChemicalsDiversified ChemicalsPaper ...
Real Estate,2792,CBRE GroupWeyerhaeuserJones Lang LaSalleRealog...,"75,00010,40077,30011,8004,5072,20,0004,050",3003.0,"$13,072$7,902$6,804$5,810$5,786$5,488$5,435",20.4%11.6%14.0%1.8%21.3%1.9%3.2%,"$572.0$1,027.0$318.2$213.0$956.4$762.0$1,838.9",4.5%103.0%-27.5%15.8%39.6%36.6%0.6%,"$10,780$19,243$7,629$7,421$30,879$11,408$31,104","$11,753$25,451$5,043$4,173$51,921$13,794$53,732",Real Estate ServicesTimber REITsReal Estate Se...
Utilities,7213,ExelonDuke EnergySouthernPG&E Corp.American El...,"34,39628,79832,01524,00017,63414,70019,00015,7...",6591.0,"$31,360$23,369$19,896$17,666$16,380$16,155$14,...",6.5%-1.0%13.8%4.9%-3.1%-7.6%-4.5%-3.1%-15.8%-3...,"$1,134.0$2,152.0$2,448.0$1,393.0$610.9$2,912.0...",-50.0%-23.6%3.4%59.4%-70.2%5.8%-469.3%--4.4%28...,"$1,14,904$1,32,761$1,09,697$68,598$63,468$89,9...","$33,309$57,397$49,335$33,696$33,009$60,099$7,3...",Multi-UtilitiesMulti-UtilitiesElectric Utiliti...